[tool.poetry]
name = "fast_bioservices"
version = "0.1.1"
description = ""
authors = ["Josh Loecker <joshloecker@icloud.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = ">=3.8,<3.12"
appdirs = "^1.4.4"
httpx = "0.27.0"
httpx-cache = "0.13.0"
pandas = { version = ">1.5.8,<3", extras = ["pyarrow"] }
rich = "^13.7.1"


[tool.poetry.group.test.dependencies]
yappi = "^1.6.0"
pytest = "^8.0"
pytest-xdist = "^3.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
