[tool.poetry]
name = "fast-bioservices"
version = "0.1.0"
description = ""
authors = ["Josh Loecker <joshloecker@icloud.com>"]
readme = "README.md"

[tool.ruff]
exclude = ["__init__.py"]


[tool.poetry.dependencies]
python = ">=3.8,<3.12"
appdirs = "^1.4.4"
pandas = { version = ">1.5.8,<3", extras = ["pyarrow"] }
requests = "^2.31.0"
requests-cache = "<2"
modguard = "^0"
tqdm = ">=4.42.0"

[tool.poetry.group.test.dependencies]
yappi = "^1.6.0"
pytest = "^8.0"
pytest-xdist = "^3.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
