[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "fast_bioservices"
version = "0.1.1"
description = ""
authors = ["Josh Loecker <joshloecker@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<4"
appdirs = "^1.4.4"
pandas = { version = ">1.5.8,<3", extras = ["pyarrow"] }
rich = "^13.7.1"

[tool.poetry.group.test.dependencies]
yappi = "^1.6.0"
pytest = "^8.2.2"
pytest-xdist = "^3.6.1"

[tool.ruff]
line-length = 120
